## Feature Construction
* Creating features
* Feature splitting
* New feature

In [ ]:
### ex-  sibling / parent => family (single feature)
### family type(alone, small, large)

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [138]:
df = pd.read_csv(r'c:\Users\rajku\Downloads\train (1).csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [139]:
df.head(15)

     Age  Pclass  SibSp  Parch  Survived
0   22.0       3      1      0         0
1   38.0       1      1      0         1
2   26.0       3      0      0         1
3   35.0       1      1      0         1
4   35.0       3      0      0         0
5    NaN       3      0      0         0
6   54.0       1      0      0         0
7    2.0       3      3      1         0
8   27.0       3      0      2         1
9   14.0       2      1      0         1
10   4.0       3      1      1         1
11  58.0       1      0      0         1
12  20.0       3      0      0         0
13  39.0       3      1      5         0
14  14.0       3      0      0         0

In [149]:
df.dropna(inplace=True)
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [150]:
print(df.isnull().sum())
print(df.isnull().sum().sum())

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64
0

In [142]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=21))

np.float64(0.69187675070028)

In [153]:
x['familiy_size'] = x['Parch'] + x['SibSp'] +1
x

      Age  Pclass  SibSp  Parch  familiy_size
0    22.0       3      1      0             2
1    38.0       1      1      0             2
2    26.0       3      0      0             1
3    35.0       1      1      0             2
4    35.0       3      0      0             1
..    ...     ...    ...    ...           ...
885  39.0       3      0      5             6
886  27.0       2      0      0             1
887  19.0       1      0      0             1
889  26.0       1      0      0             1
890  32.0       3      0      0             1

[714 rows x 5 columns]

In [144]:
def funct(num):
    if num ==1:
        return 0
    elif num >1 and num <=4:
        return 1
    else:
        return 2

In [155]:
x['family_type'] = x['familiy_size'].apply(funct)

In [146]:
x

      Age  Pclass  SibSp  Parch  familiy_size  family_type
0    22.0       3      1      0             2            1
1    38.0       1      1      0             2            1
2    26.0       3      0      0             1            0
3    35.0       1      1      0             2            1
4    35.0       3      0      0             1            0
..    ...     ...    ...    ...           ...          ...
885  39.0       3      0      5             6            2
886  27.0       2      0      0             1            0
887  19.0       1      0      0             1            0
889  26.0       1      0      0             1            0
890  32.0       3      0      0             1            0

[714 rows x 6 columns]

In [157]:
x.drop(columns=['SibSp','Parch','familiy_size'], inplace=True)

In [158]:
x.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [159]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

## Feature Splitting

In [160]:
df = pd.read_csv(r'c:\Users\rajku\Downloads\train (1).csv')

In [161]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [163]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [164]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [165]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: object

In [166]:
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [168]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64